server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 1KB
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  # tomcat配置
  tomcat:
    # 允许最大连接数,默认8192,当达到临界值时,系统会基于accept-count继续接受连接 参数是客户感知型参数。
    max-connections: 8192
    # 当所有线程都在使用时,建立连接的请求的等待队列长度,默认100 请求的backlog值 如果超过max-connections和accept-count总和，新的连接会被拒绝，即直接拒绝服务（直接返回connection refused）
    accept-count: 100
    # 连接器在关闭空闲连接之前等待的毫秒数，默认 20000 20s
    connection-timeout: 20s
    uri-encoding: UTF-8
    threads:
      # 线程池的最小工作线程数,默认10
      min-spare: 50
      # 线程池的最大线程数,默认200
      max: 1000
  servlet:
    context-path: /

info:
  author: shucan
  version: 1.0.0

logger:
  config: classpath:logback.xml

weather:
  key: c50d8fc68ade4c6590267b3730c3e505
  public-id: HE2403210909151725
